### PR TITLE
Change all non-https download linkt to https

### PR DESCRIPTION
**Pull request by hajee**
The http links for downloading the software don't seem to work anymore. Changed all http links to https links.

### CODE REVIEW

**Comment by hajee** [comment]
Unfortunately the http links don't work for me. 

```
RROR:  Error installing ibm_db:
	ERROR: Failed to build gem native extension.
    current directory: /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/ibm_db-5.4.0/ext
/opt/puppetlabs/puppet/bin/ruby -I /opt/puppetlabs/puppet/lib/ruby/2.7.0 -r ./siteconf20230319-509-z1i9b4.rb extconf.rb
extconf.rb:70: warning: already initialized constant DOWNLOADLINK
extconf.rb:45: warning: previous definition of DOWNLOADLINK was here
/opt/puppetlabs/puppet/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to public.dhe.ibm.com:80 (Connection refused - connect(2) for "public.dhe.ibm.com" port 80) (Errno::ECONNREFUSED)

```

Can you please make a new release of the gem with this fix?

**Comment by praveen-db2** [comment]
@hajee As of now we request you to install ibm_db gem cloning via Git repo. We will consider it releasing official GEM in some time. As of now we have other priorities.

**Comment by hajee** [comment]
Unfortunately we have customers that won't/can't do that. 

You said the http-links should still work. If you can point out to us why it is failing on our side, and we can fix that, then we don't need a quick release.

If you like, I can prepare a PR with all the stuff needed for a new release. You'll only have to merge, build and release.

**Comment by praveen-db2** [comment]
@hajee released new gem version 5.4.1 released. Please check and let me know if it works for you and the same for your customers.

**Comment by hajee** [comment]
Works fine. Thanks for the release

**Pull request merged**
